api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "ibc-delivery-gate"
type = "function"
uid = "5100d166-8e0d-4cd4-1f59-b983ddb5cc7a1bb6f08c"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
