api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "ibc-checkout-guard"
type = "function"
uid = "f73d73b6-6798-e592-b296-8aa3bc224edf9ecc168f"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
